labs/lab3/blog/blog/apps/articles/urls.py
from django.urls import path
from django.conf.urls import include, url

from . import views

app_name = 'articles'

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:article_id>/', views.detail, name='detail'),
    path('<int:article_id>/leave_comment/', views.leave_comment, name='leave_comment'),
    path('new', views.create_post, name='new'),
    url(r'^register/$', views.RegisterFormView.as_view(), name='register'),
    url(r'^login/$', views.LoginFormView.as_view(), name='login'),
    url(r'^logout/$', views.logout_, name='logout'),
    # path('test/', views.test, name='test')
]

labs/lab3/blog/blog/urls.py
from django.contrib import admin
from django.shortcuts import redirect
from django.urls import path, include
import grappelli

urlpatterns = [
    path('', include('articles.urls')),
    path('articles/', include('articles.urls')),
    path('grappelli/', include('grappelli.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
]

labs/lab3/blog/blog/apps/articles/models.py
import datetime
from django.db import models

from django.utils import timezone


class Article(models.Model):
	article_title = models.CharField('название статьи', max_length=200)
	article_author = models.CharField('Автор', max_length=200, default='Автор статьи')
	article_text = models.TextField('текст статьи')
	pub_date = models.DateTimeField('дата публикации', default=timezone.now())

	def __str__(self):
		return self.article_title

	def was_published_recently(self):
		return self.pub_date >= (timezone.now() - datetime.timedelta(days=7))

	class Meta:
		verbose_name='Статья'
		verbose_name_plural='Статьи'

	def __unicode__(self):
		return "%s: %s" % (self.article_author, self.article_title)

	def get_excerpt(self):
		return self.article_text[:140] + "..." if len(self.article_text) > 140 else self.article_text

	get_excerpt.short_description = "Отрывок статьи"


class Comment(models.Model):
	article = models.ForeignKey(Article, on_delete=models.CASCADE)
	author_name = models.CharField('имя автора', max_length=50)
	comment_text = models.CharField('текст комментария', max_length=300)

	def __str__(self):
		return self.author_name

	class Meta:
		verbose_name = 'Комментарий'
		verbose_name_plural = 'Комментарии'

labs/lab3/blog/blog/apps/articles/views.py
from django.shortcuts import render, redirect
from django.http import Http404
from django.urls import reverse
from django.http import HttpResponseRedirect
from django.contrib.auth import logout
from django.views.generic.edit import FormView
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import login

from .models import Article, Comment


def index(request):
    latest_articles_list = Article.objects.order_by('-pub_date')[:5]
    return render(request, 'articles/list.html', {'latest_articles_list': latest_articles_list})


def detail(request, article_id):
    try:
        a = Article.objects.get(id=article_id)
    except:
        raise Http404("Статья не найдена!")

    latest_comments_list = a.comment_set.order_by('-id')[:10]

    return render(request, 'articles/detail.html', {'article': a, 'latest_comments_list': latest_comments_list})


def leave_comment(request, article_id):
    try:
        a = Article.objects.get(id=article_id)
    except:
        raise Http404("Статья не найдена!")

    a.comment_set.create(author_name=request.POST['name'], comment_text=request.POST['text'])
    return HttpResponseRedirect(reverse('articles:detail', args=(a.id,)))


def create_post(request):
    if not request.user.is_anonymous:
        # Здесь будет основной код представления
        if request.method == "POST":
            # обработать данные формы, если метод POST
            form = {
                'text': request.POST["text"],
                'title': request.POST["title"]
            }
            # в словаре form будет храниться информация, введенная пользователем
            if form["text"] and form["title"] and check_unique(form["title"]):
                # если поля заполнены без ошибок

                article = Article.objects.create(article_text=form["text"],
                                                 article_author=request.user,
                                                 article_title=form["title"])
                return HttpResponseRedirect(reverse('articles:detail', args=(article.id,)))
            # перейти на страницу поста
            else:
                # если введенные данные некорректны
                form['errors'] = u"Не все поля заполнены"
                return render(request, 'articles/create_post.html', {'form': form})
        else:
            # просто вернуть страницу с формой, если метод GET
            return render(request, 'articles/create_post.html', {})
    else:
        raise Http404


def check_unique(title_string):
    articles = Article.objects.filter(article_title=title_string)
    if len(articles) > 0:
        return False
    else:
        return True


def logout_(request):
    logout(request)
    return HttpResponseRedirect("/")


class RegisterFormView(FormView):
    form_class = UserCreationForm
    success_url = "/login/"
    template_name = "register.html"

    def form_valid(self, form):
        form.save()
        return super(RegisterFormView, self).form_valid(form)


class LoginFormView(FormView):
    form_class = AuthenticationForm
    template_name = "login.html"
    success_url = "/"

    def form_valid(self, form):
        self.user = form.get_user()
        login(self.request, self.user)
        return super(LoginFormView, self).form_valid(form)

labs/lab3/blog/blog/templates/articles/create_post.html
<!DOCTYPE html>
<html>
<head>
    <title>Django Public Blog - создать статью</title>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'articles/stylesheets/create_form.css' %}">
</head>
<body>

{% load static %}
<img src="{% static 'articles/img/django-logo-negative.png' %}" alt="">

<div class="content">
    <h1 class="title">Написать новую статью</h1>
    <form class="form" method="POST">
        {% csrf_token %}
        <div class="form_div">
            <input type="text" name="title" placeholder="Название статьи" value="{{ form.title }}">
        </div>
        <div class="form_div">
            <textarea name="text" placeholder="Текст статьи">{{ form.text }}</textarea>
        </div>
        <div class="form_div">
            <input type="submit" class="btn_save" value="Сохранить">
        </div>
        <p></p>
    </form>
    {{ form.errors }}
</div>
</body>
</html>

labs/lab3/blog/blog/templates/articles/detail.html
{% extends 'base.html' %}

{% block title %}  {{ article.article_title }}  {% endblock %}

{% block content %}
    <div class="link_to_new">
        <a href="{% url 'articles:new' %}">Новая статья</a>
    </div>
    <div class="link_to_list">
        <a href="{% url 'articles:index' %}">Все статьи</a>
    </div>

    <div class="information">
        <h2 class="article_title"> {{ article.article_title }}</h2>
        <h2 class="author"> Автор статьи: {{ article.article_author }}</h2>

    </div>
    <em class="pub_date">Дата публикации: {{ article.pub_date }}</em>
    {% if article.was_published_recently %}
        <p class="new_article">НОВАЯ СТАТЬЯ!</p>
    {% endif %}

    <p class="article_text">{{ article.article_text }}</p>


    <hr>
    {% if latest_comments_list %}

        {% for c in latest_comments_list %}
            <p>
                <strong>{{ c.author_name }}</strong>
            <p>{{ c.comment_text }}</p>
            </p>
        {% endfor %}

    {% else %}
        Комментарии не найдены! Станьте первым :)
        <p></p>
    {% endif %}
    <hr>
    <p></p>
    <form action="{% url 'articles:leave_comment' article.id %}" method="POST">

        {% csrf_token %}

        <input type="text" required placeholder="Ваще имя" name="name"> <br>
        <textarea name="text" required="" placeholder="Текст комментария" cols="30" rows="10"></textarea> <br>

        <button type="submit">Оставить комментарий</button>
    </form>


{% endblock %}

labs/lab3/blog/blog/templates/articles/list.html
{% extends 'base.html' %}

{% block title %} Последние статьи {% endblock %}

{% block content %}
    <div class="entering">
        {% if request.user.is_anonymous %}
            <a href="{% url 'articles:register' %}" class="entering_links">Регистрация</a> <br>
            <a href="{% url 'articles:login' %}" class="entering_links">Вход</a> <br>
        {% else %}
            <p>Вход выполнен под пользоватедем: {{ request.user.username }} </p>
            <a href="{% url 'articles:logout' %}" class="entering_links">Выход</a> <br>
        {% endif %}
    </div>
    {% if latest_articles_list %}

        {% for a in latest_articles_list %}
            <div class="article">
                <a href="{% url 'articles:detail' a.id %}" class="link_to_article">{{ a.article_title }} </a> <br>
                <p class="author">{{ a.article_author }}</p>
                <p class="pub_date">{{ a.pub_date  }}</p>
                <p class="article_text">{{ a.get_excerpt }}</p>
            </div>

        {% endfor %}
    {% else %}
        Статьи не найдены )=
    {% endif %}

{% endblock %}

labs/lab3/blog/blog/templates/base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'articles/stylesheets/index.css' %}">
    <title>{%  block title %} Мой сайт {% endblock %}</title>

</head>
<body>
{% load static %}
<img src="{% static 'articles/img/django-logo-negative.png' %}" alt="">
    {%  block content %} Мой сайт {% endblock %}
</body>
</html>

labs/lab3/blog/blog/templates/base_generic.html
<!DOCTYPE html>
<html lang="en">
<head>
  {% block title %}<title>Local Library</title>{% endblock %}
</head>

<body>
  {% block sidebar %}<!-- insert default navigation text for every page -->{% endblock %}
  {% block content %}<!-- default content text (typically empty) -->{% endblock %}
</body>
</html>

labs/lab3/blog/blog/templates/login.html
<!DOCTYPE html>
<html>
  <head>
    <title>Авторизация</title>
      {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static '/articles/stylesheets/login_register.css' %}">
  </head>
  <body>
    <form action="" method="post">
      {% csrf_token %}
      {{ form.as_p }}
      <button type="submit">Войти</button>
    </form>
  </body>
</html>

labs/lab3/blog/blog/templates/register.html
<!DOCTYPE html>
<html>
  <head>
    <title>Регистрация</title>
      {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static '/articles/stylesheets/login_register.css' %}">
  </head>
  <body>
    <form action="" method="post">
      {% csrf_token %}
      {{ form.as_p }}
      <button type="submit">Зарегистрироваться</button>
    </form>
  </body>
</html>